version: "3.3"

services:
    
    gripper_server:
        image: frogs_fm_gripper
        container_name: frogs_fm_gripper_server
        network_mode: host
        privileged: true
        volumes:
        - ../:/home/ros
        - /tmp/.X11-unix:/tmp/.X11-unix:rw 
        - /dev/ttyACM0:/dev/ttyACM0 
        # depends_on:
        #  - frogs_manager

        environment:
        - DISPLAY=$DISPLAY
        - QT_X11_NO_MITSHM=1
        #- "ROS_MASTER_URI=http://frogs:11311"

        command: bash -c "/home/ros/gripper.sh"
        



    gripper_driver:
        image: frogs_fm_gripper
        container_name: frogs_fm_gripper
        network_mode: host
        volumes:
        - ../:/home/ros
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - /dev/:/dev/
        # depends_on:
        #  - frogs_manager
        privileged: true
        #devices:
        #- /dev/ttyUSB0

        environment:
        - DISPLAY=$DISPLAY
        - QT_X11_NO_MITSHM=1
        #- "ROS_MASTER_URI=http://frogs:11311"

        command: bash #-c "/home/ros/gripper_driver.sh"
     

