; Auto-generated. Do not edit!


(cl:in-package fm_gripper_msgs-msg)


;//! \htmlinclude FmGripperActionGoal.msg.html

(cl:defclass <FmGripperActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type fm_gripper_msgs-msg:FmGripperGoal
    :initform (cl:make-instance 'fm_gripper_msgs-msg:FmGripperGoal)))
)

(cl:defclass FmGripperActionGoal (<FmGripperActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FmGripperActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FmGripperActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name fm_gripper_msgs-msg:<FmGripperActionGoal> is deprecated: use fm_gripper_msgs-msg:FmGripperActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <FmGripperActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader fm_gripper_msgs-msg:header-val is deprecated.  Use fm_gripper_msgs-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <FmGripperActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader fm_gripper_msgs-msg:goal_id-val is deprecated.  Use fm_gripper_msgs-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <FmGripperActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader fm_gripper_msgs-msg:goal-val is deprecated.  Use fm_gripper_msgs-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FmGripperActionGoal>) ostream)
  "Serializes a message object of type '<FmGripperActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FmGripperActionGoal>) istream)
  "Deserializes a message object of type '<FmGripperActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FmGripperActionGoal>)))
  "Returns string type for a message object of type '<FmGripperActionGoal>"
  "fm_gripper_msgs/FmGripperActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FmGripperActionGoal)))
  "Returns string type for a message object of type 'FmGripperActionGoal"
  "fm_gripper_msgs/FmGripperActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FmGripperActionGoal>)))
  "Returns md5sum for a message object of type '<FmGripperActionGoal>"
  "a3b6c7a3d60a4f98b9d3c514fdad29fd")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FmGripperActionGoal)))
  "Returns md5sum for a message object of type 'FmGripperActionGoal"
  "a3b6c7a3d60a4f98b9d3c514fdad29fd")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FmGripperActionGoal>)))
  "Returns full string definition for message of type '<FmGripperActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%FmGripperGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: fm_gripper_msgs/FmGripperGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal         ~%int64 distance~%int64 velocity~%int64 force~%bool calibrate~%bool reset~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FmGripperActionGoal)))
  "Returns full string definition for message of type 'FmGripperActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%FmGripperGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: fm_gripper_msgs/FmGripperGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal         ~%int64 distance~%int64 velocity~%int64 force~%bool calibrate~%bool reset~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FmGripperActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FmGripperActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'FmGripperActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
