// Generated by gencpp from file fm_gripper_msgs/FmGripperResult.msg
// DO NOT EDIT!


#ifndef FM_GRIPPER_MSGS_MESSAGE_FMGRIPPERRESULT_H
#define FM_GRIPPER_MSGS_MESSAGE_FMGRIPPERRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fm_gripper_msgs
{
template <class ContainerAllocator>
struct FmGripperResult_
{
  typedef FmGripperResult_<ContainerAllocator> Type;

  FmGripperResult_()
    : result(0)  {
    }
  FmGripperResult_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int64_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::fm_gripper_msgs::FmGripperResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fm_gripper_msgs::FmGripperResult_<ContainerAllocator> const> ConstPtr;

}; // struct FmGripperResult_

typedef ::fm_gripper_msgs::FmGripperResult_<std::allocator<void> > FmGripperResult;

typedef boost::shared_ptr< ::fm_gripper_msgs::FmGripperResult > FmGripperResultPtr;
typedef boost::shared_ptr< ::fm_gripper_msgs::FmGripperResult const> FmGripperResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fm_gripper_msgs::FmGripperResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fm_gripper_msgs::FmGripperResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fm_gripper_msgs::FmGripperResult_<ContainerAllocator1> & lhs, const ::fm_gripper_msgs::FmGripperResult_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fm_gripper_msgs::FmGripperResult_<ContainerAllocator1> & lhs, const ::fm_gripper_msgs::FmGripperResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fm_gripper_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::fm_gripper_msgs::FmGripperResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fm_gripper_msgs::FmGripperResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fm_gripper_msgs::FmGripperResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fm_gripper_msgs::FmGripperResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fm_gripper_msgs::FmGripperResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fm_gripper_msgs::FmGripperResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fm_gripper_msgs::FmGripperResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b05623554ab950ed237d43d45f0b4dd";
  }

  static const char* value(const ::fm_gripper_msgs::FmGripperResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b05623554ab950eULL;
  static const uint64_t static_value2 = 0xd237d43d45f0b4ddULL;
};

template<class ContainerAllocator>
struct DataType< ::fm_gripper_msgs::FmGripperResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fm_gripper_msgs/FmGripperResult";
  }

  static const char* value(const ::fm_gripper_msgs::FmGripperResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fm_gripper_msgs::FmGripperResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result\n"
"int64 result\n"
;
  }

  static const char* value(const ::fm_gripper_msgs::FmGripperResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fm_gripper_msgs::FmGripperResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FmGripperResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fm_gripper_msgs::FmGripperResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fm_gripper_msgs::FmGripperResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int64_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FM_GRIPPER_MSGS_MESSAGE_FMGRIPPERRESULT_H
